[package]
name = "actix-web-demo-2"
version = "0.2.1"
edition = "2018"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
[dependencies]
postgres = "0.17"
actix-web = "1.0.7"
serde = { version = "1.0.101", features = ["derive"] }
env_logger = "0.6"
